<a href="https://colab.research.google.com/github/laksiri-kingslake/neural-network-from-scratch/blob/main/NeuralNetworks_Coding_From_Scratch_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS

### CODING OUR FIRST NEURON: 3 INPUTS

![Neuron with 3 inputs](./images/neuron-3-input.png)

In [1]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

outputs = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)

print(outputs)

2.3


In [ ]:
import numpy as np
X = np.array(inputs)
W = np.array(weights)
outputs = np.dot(X, W.transpose()) + bias
print(outputs)

# print dimensions of X and W
print("Dimensions of X:", X.shape)
print("Dimensions of W:", W.shape)

2.3
Dimensions of X: (3,)
Dimensions of W: (3,)


### CODING OUR SECOND NEURON: 4 INPUTS ###

![Neuron with 4 inputs](./images/neuron-4-input.png)

In [9]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0]*weights[0] +
 inputs[1]*weights[1] +
 inputs[2]*weights[2] +
 inputs[3]*weights[3] + bias)

print(output)

4.8


In [10]:
output = np.dot(inputs, weights) + bias
print(output)

4.8


### CODING OUR FIRST LAYER

![A layer of neurons](./images/neuron-layer.png)

In [11]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0] #LIST OF WEIGHTS ASSOCIATED WITH 1ST NEURON : W11, W12, W13, W14
weights2 = weights[1] #LIST OF WEIGHTS ASSOCIATED WITH 2ND NEURON : W21, W22, W23, W24
weights3 = weights[2] #LIST OF WEIGHTS ASSOCIATED WITH 3RD NEURON : W31, W32, W33, W34

biases = [bias1, bias2, bias3] = [2, 3, 0.5]

outputs = [
 # Neuron 1:
 inputs[0]*weights1[0] +
 inputs[1]*weights1[1] +
 inputs[2]*weights1[2] +
 inputs[3]*weights1[3] + bias1,
 # Neuron 2:
 inputs[0]*weights2[0] +
 inputs[1]*weights2[1] +
 inputs[2]*weights2[2] +
 inputs[3]*weights2[3] + bias2,
 # Neuron 3:
 inputs[0]*weights3[0] +
 inputs[1]*weights3[1] +
 inputs[2]*weights3[2] +
 inputs[3]*weights3[3] + bias3]

print(outputs)

[4.8, 1.21, 2.385]


In [14]:
X = np.array(inputs)
W = np.array(weights)

outputs = np.dot(X, W.transpose()) + biases
print(outputs)

[4.8   1.21  2.385]


In [15]:
# shape of X and W
print("Shape of X:", X.shape)
print("Shape of W:", W.shape)

Shape of X: (4,)
Shape of W: (3, 4)


### USING LOOPS FOR BETTER AND EASIER CODING

In [16]:
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
  # Zeroed output of given neuron
  neuron_output = 0
  # For each input and weight to the neuron
  for n_input, weight in zip(inputs, neuron_weights):
    # Multiply this input by associated weight
    # and add to the neuron's output variable
    neuron_output += n_input*weight ## W31*X1 + W32*X2 + W33*X3 + W34*X4
  # Add bias
  neuron_output += neuron_bias ## ## W31*X1 + W32*X2 + W33*X3 + W34*X4 + B3
  # Put neuron's result to the layer's output list
  layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


### USING NUMPY

#### NumPy dot Product 

1. NumPy dot Product of Vectors

    x = [a1, a2, a3]

    y = [b1, b2, b3]

    np.dot(x, y) = a1*b1 + a2*b2 + a3*b3

In [17]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))  # Output: 32

32


2. NumPy dot product of vector and matrix

    x = [a1, a2, a3] # 1 x 3

    y = [[b11, b12, b13],<br>
         [b21, b22, b23],<br>
         [b31, b32, b33]] # 3 x 3

    np.dot(x, y) = [a1*b11 + a2*b21 + a3*b31, a1*b12 + a2*b22 + a3*b32, a1*b13 + a2*b23 + a3*b33] # 1 x 3

    Let's call<br>
    bn1 = [b11,b21,b31]<br>
    bn2 = [b12,b22,b32]<br>
    bn3 = [b13,b23,b33]<br>
    Then,<br>
    np.dot(x, y) = [np.dot(x,bn1), np.dot(x,bn2), np.dot(x,bn3)] # 1 x 3

    np.dot(y, x) = [[np.dot(bn1, x)],[np.dot(bn2, x)],[np.dot(bn3, x)]]

In [18]:
y = np.array([[4, 5, 6],[7, 8, 9],[10, 11, 12]]) # 3 x 3 matrix
print(np.dot(x, y))  # Output: 48 54 60 1 x 3 matrix (vector)

[48 54 60]


In [19]:
print(np.dot(y, x)) # Output: [32  50  48] 3 x 1 matrix (vector)

[32 50 68]


3. NumPy dot product of a matrix and a matrix

    a = [[a11, a12],<br>
         [a21, a22],<br>
         [a31, a32]]<br> # 3 x 2 matrix

    y = [[b11, b12, b13],<br>
         [b21, b22, b23]] # 2 x 3 matrix<br>

    Let's call<br>
    a1 = [a11, a12]<br>
    a2 = [a21, a22]<br>
    a3 = [a31, a32]<br>
    bn1 = [b11,b21]<br>
    bn2 = [b12,b22]<br>
    bn3 = [b13,b23]<br>
    Then,<br>

    np.dot(a, b) = [[np.dot(a1,bn1), np.dot(a1,bn2), np.dot(a1,bn3)],<br>
                    [np.dot(a2,bn1), np.dot(a2,bn2), np.dot(a2,bn3)],<br>
                    [np.dot(a3,bn1), np.dot(a3,bn2), np.dot(a3,bn3)]]     # 3 x 3 matrix

In [20]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # 3 x 2 matrix

b = np.array([[7, 8, 9],
              [10, 11, 12]]) # 2 x 3 matrix

print(np.dot(a, b)) # Output: [[27 30 33] [61 68 75] [95 106 117]] 3 x 3 matrix


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


### SINGLE NEURON USING NUMPY

![A neuron with np dot product](./images/neuron-np-dot.png)

In [21]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


### LAYER OF NEURONS USING NUMPY

![A neuron layer with np dot product](./images/neuron-layer-np-dot.png)

In [ ]:
##  In plain Python, we wrote this as a list of lists. With NumPy, this will be a 2-dimensional array, which we’ll call a matrix.

In [22]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vector results in a list of dot products.
#The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other vector

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

new_outputs = np.dot(inputs, np.transpose(weights)) + np.transpose(biases)
print(new_outputs)

[4.8   1.21  2.385]
[4.8   1.21  2.385]


### LAYER OF NEURONS AND BATCH OF DATA USING NUMPY

![A neuron layer with a batch of input](./images/neuron-layer-with-input-batch.png)

###### NEED TO TAKE TRANSPOSE OF WEIGHT MATRIX

![Get transpose of weights matrix](./images/neuron-layer-with-input-batch-weights-transpose.png)

In [23]:
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# NOTE: WE CAN'T TRANSPOSE LISTS IN PYTHON, SO WE HAVE THE CONVERT THE WEIGHTS MATRIX INTO AN ARRAY FIRST
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


### MULTIPLE LAYERS WITH A BATCH OF DATA USING NUMPY

![Multiple layers with a batch of data](./images/multiple-neuron-layers.png)

In [24]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

# print(layer2_outputs)

weights3 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33]]

biases3 = [1, -1]

weights3_array = np.array(weights3)
biases3_array = np.array(biases3)

layer3_outputs = np.dot(layer2_outputs, weights3_array.T) + biases3_array
print(layer3_outputs)

[[ 0.176794  -0.7037845]
 [-1.474662   0.452205 ]
 [ 0.5246554 -0.2162637]]


## Dense Layer Class

We write python class named `Layer_Dense` to encapsulate the functionality.

The class has two main methods `__init__` and `forward`

![Dense Layer Class - Inputs and Neurons](./images/dense_layer_class_inputs_and_neurons.png)

Here we take 2 inputs and 3 neurons in the neural network

For wight matrix we already consider transpose so that it is not required to take transpose at the time of evaluation

#### Matrix calculations for the exercise

In [14]:
import numpy as np

x1 = np.array([[1, 2, 3]])
print(x1.shape) # Output: (1, 3)

x2 = np.array([[1], [2], [3]])
print(x2.shape) # Output: (3, 1)

x3 = np.random.randn(2, 3)
print(x3.shape) # Output: (2, 3)
print(x3)

x4 = np.zeros((1, 3))
print(x4.shape) # Output: (1, 3)
print(x4)

x4 = np.random.rand(100, 2)
x5 = np.random.rand(2, 3)
x6 = np.random.rand(1, 3)
x7 = np.dot(x4, x5) + x6
print(x7.shape) # Output: (100, 3)
print(x7)

(1, 3)
(3, 1)
(2, 3)
[[-1.1268258  -0.7306777  -0.3848798 ]
 [ 0.09435159 -0.04217145 -0.2868872 ]]
(1, 3)
[[0. 0. 0.]]
(100, 3)
[[0.54983665 1.15726566 0.5245564 ]
 [0.69883578 1.17843239 0.54019992]
 [0.52857816 1.02387966 0.37251366]
 [0.72171454 1.38022663 0.77075996]
 [1.68284251 1.71460275 1.09901695]
 [0.85019837 1.15017238 0.49890678]
 [1.18553783 1.37429766 0.73692541]
 [1.37989761 1.16990082 0.49071877]
 [1.25641449 1.27424361 0.6178187 ]
 [0.85905059 1.42305078 0.8119707 ]
 [0.86471002 1.42565317 0.81463154]
 [1.04493006 1.31895535 0.68152   ]
 [1.03414889 1.24295039 0.59480657]
 [1.22544147 1.33875449 0.69375612]
 [1.03171785 1.53714751 0.93302636]
 [1.31072982 1.14989661 0.47176039]
 [0.74269845 1.23630393 0.60414799]
 [1.52658619 1.69047861 1.08039771]
 [1.64838947 1.66342585 1.04221396]
 [1.02571119 1.62515561 1.03451132]
 [0.67568462 1.09515385 0.44584868]
 [1.40030481 1.26413022 0.5978141 ]
 [1.0867116  1.12581046 0.45713243]
 [1.40918078 1.61790375 1.00383775]
 [0.791

#### Implementation

In [11]:
%%capture
!pip install nnfs

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) 
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

# Create dataset
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Perform a forward pass of our training data through this layer
dense1.forward(X)

print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


Note the shape of the matrixes

```
X --> (100, 2)
W --> (2, 3) --> input, neurons
b --> (1, 3)
```

`y = np.dot(X, W) + b --> (100, 2) x (2, 3) + (1, 3) --> (100, 3) + (1, 3) --> (100, 3)`

### Activation Function

#### Sigmoid Activation Function 

$$ \sigma(x) = \frac{1}{1 + e^{-x}} $$
<img src="./images/sigmoid.jpg" width="250">