### Array Operations

#### Array Summation

In [1]:
import numpy as np

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = np.array(A)

print(np.sum(A))  # Output: 45
print(B.sum())  # Output: 45
print(B.sum(axis=None))  # Output: 45

# 1 dimension arrays
print(B.sum(axis=0))  # Output: [12 15 18] (sum of each column)
print(B.sum(axis=1))  # Output: [ 6 15 24] (sum of each row)

# 2 dimension arrays
print(B.sum(axis=0, keepdims=True))  # Output: [12 15 18] (sum of each column)
print(B.sum(axis=1, keepdims=True))  # Output: [ 6 15 24] (sum of each row)

45
45
45
[12 15 18]
[ 6 15 24]
[[12 15 18]]
[[ 6]
 [15]
 [24]]


### NumPy Array Broadcasting Rules

A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]] <br>
B = [[1, 2, 3]]

**Dimensions**<br>
A: 3 x 3<br>
B: 1 x 3

**Rule**<br>
Scan from left<br>
- One dimension must be equal
- One dimension must be 1 or should not exists

Then, dimension 1 or none will be broadcasted to satisfy so that the operation is valid

A : $ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} $ `+` B : $ \begin{pmatrix} 1 & 2 & 3 \end{pmatrix} $

B : $ \begin{pmatrix} 1 & 2 & 3 \end{pmatrix} $
--> Broadcasting
$ \begin{pmatrix} 1 & 2 & 3 \\ 1 & 2 & 3 \\ 1 & 2 & 3 \end{pmatrix} $


In [2]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1, 2, 3]]

A = np.array(A)
B = np.array(B)

C = A + B
print(C)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [3]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1], [2], [3]]

A = np.array(A)
B = np.array(B)

C = A + B
print(C)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [4]:
D = [1,2,3]
arrD = np.array(D)
arrD = arrD.reshape(3,1)
print(arrD.shape)
print(arrD)

(3, 1)
[[1]
 [2]
 [3]]


A = $ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} $

Subtract row max from each element. That is,  
Row 1 --> 3  
Row 2 --> 6  
Row 3 --> 9



In [5]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A = np.array(A)

B = np.max(A, axis=1)
print(B)
print(B.shape) # 1 dimension array. In operation A - B, it will be broadcasted as 1 x 3

C = np.max(A, axis=1, keepdims=True)
print(C)
print(C.shape)

D = A - C  # = A - B.reshape(3,1)
print(D)

[3 6 9]
(3,)
[[3]
 [6]
 [9]]
(3, 1)
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [6]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(np.sum(A))

print(np.sum(A, axis=0))  # sum of each column
print(np.sum(A, axis=0).shape)

print(np.sum(A, axis=1))  # sum of each row
print(np.sum(A, axis=1).shape)

print(np.sum(A, axis=0, keepdims=True))  # sum of each row
print(np.sum(A, axis=0, keepdims=True).shape)

print(np.sum(A, axis=1, keepdims=True))  # sum of each row
print(np.sum(A, axis=1, keepdims=True).shape)

print(np.max(A, axis=0))  # max of each column
print(np.max(A, axis=0).shape)

print(np.max(A, axis=1))  # max of each row
print(np.max(A, axis=1).shape)

print(np.max(A))


45
[12 15 18]
(3,)
[ 6 15 24]
(3,)
[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)
[7 8 9]
(3,)
[3 6 9]
(3,)
9


In [4]:
import numpy as np
A = [1, 2] 
A = np.array(A)
print(A.shape)  # Output: (2,)

B = [[1, 2], [3, 4], [5, 6]]
B = np.array(B)
print(B.shape)  # Output: (3, 2)

C = [[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]], [[19, 20], [21, 22], [23, 24]]]
C = np.array(C)
print(C.shape)  # Output: (4, 3, 2)

print(A.sum(axis=0))  # Output: 3
print(B.sum(axis=0))  # Output: [9 12]
print(B.sum(axis=1))  # Output: [ 3  7 11]
print(C.sum(axis=0))  # Output: [[ 40  44] [ 48  52] [ 56  60]]
print(C.sum(axis=1))  # Output: [[ 15  18] [ 39  42] [ 63  66] [ 87  90]]
print(C.sum(axis=2))  # Output: [[ 6 14 22] [ 30 38 46] [ 54 62 70] [ 78 86 94]]

(2,)
(3, 2)
(4, 3, 2)
3
[ 9 12]
[ 3  7 11]
[[40 44]
 [48 52]
 [56 60]]
[[ 9 12]
 [27 30]
 [45 48]
 [63 66]]
[[ 3  7 11]
 [15 19 23]
 [27 31 35]
 [39 43 47]]


In [7]:
print(A.sum(axis=0, keepdims=True))  # Output: [3]

[3]


In [8]:
print(B.sum(axis=0, keepdims=True))  # Output: [[9 12]]

[[ 9 12]]


In [9]:
print(B.sum(axis=1, keepdims=True))  # Output: [[3] [7] [11]]

[[ 3]
 [ 7]
 [11]]


In [10]:
print(C.sum(axis=0, keepdims=True))  # Output: [[[ 40  44] [ 48  52] [ 56  60]]]

[[[40 44]
  [48 52]
  [56 60]]]


In [11]:
print(C.sum(axis=1, keepdims=True))

[[[ 9 12]]

 [[27 30]]

 [[45 48]]

 [[63 66]]]


In [6]:
print(C.sum(axis=2, keepdims=True))

[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]

 [[27]
  [31]
  [35]]

 [[39]
  [43]
  [47]]]


Get specific elements from an array

In [ ]:
import numpy as np

A = np.array([[0.7, 0.1, 0.2], [0.1, 0.5, 0.4], [0.02, 0.9, 0.08 ]])

print(A[[0,1,2], [0,1,1]])

[0.7 0.5 0.9]


- row 0, column 0  --> 0.7
- row 1, column 1  --> 0.5
- row 2, column 1  --> 0.9

In [ ]:
print(len(A))
print(A[range(len(A)), [0,1,1]])  # range(len(A)) --> [0, 1, 2]

3
[0.7 0.5 0.9]
