### Array Operations

#### Array Summation

In [1]:
import numpy as np

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = np.array(A)

print(np.sum(A))  # Output: 45
print(B.sum())  # Output: 45
print(B.sum(axis=None))  # Output: 45

# 1 dimension arrays
print(B.sum(axis=0))  # Output: [12 15 18] (sum of each column)
print(B.sum(axis=1))  # Output: [ 6 15 24] (sum of each row)

# 2 dimension arrays
print(B.sum(axis=0, keepdims=True))  # Output: [12 15 18] (sum of each column)
print(B.sum(axis=1, keepdims=True))  # Output: [ 6 15 24] (sum of each row)

45
45
45
[12 15 18]
[ 6 15 24]
[[12 15 18]]
[[ 6]
 [15]
 [24]]


### NumPy Array Broadcasting Rules

A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]] <br>
B = [[1, 2, 3]]

**Dimensions**<br>
A: 3 x 3<br>
B: 1 x 3

**Rule**<br>
Scan from left<br>
- One dimension must be equal
- One dimension must be 1 or should not exists

Then, dimension 1 or none will be broadcasted to satisfy so that the operation is valid

A : $ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} $ `+` B : $ \begin{pmatrix} 1 & 2 & 3 \end{pmatrix} $

B : $ \begin{pmatrix} 1 & 2 & 3 \end{pmatrix} $
--> Broadcasting
$ \begin{pmatrix} 1 & 2 & 3 \\ 1 & 2 & 3 \\ 1 & 2 & 3 \end{pmatrix} $


In [2]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1, 2, 3]]

A = np.array(A)
B = np.array(B)

C = A + B
print(C)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [3]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1], [2], [3]]

A = np.array(A)
B = np.array(B)

C = A + B
print(C)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [4]:
D = [1,2,3]
arrD = np.array(D)
arrD = arrD.reshape(3,1)
print(arrD.shape)
print(arrD)

(3, 1)
[[1]
 [2]
 [3]]


A = $ \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} $

Subtract row max from each element. That is,  
Row 1 --> 3  
Row 2 --> 6  
Row 3 --> 9



In [5]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A = np.array(A)

B = np.max(A, axis=1)
print(B)
print(B.shape) # 1 dimension array. In operation A - B, it will be broadcasted as 1 x 3

C = np.max(A, axis=1, keepdims=True)
print(C)
print(C.shape)

D = A - C  # = A - B.reshape(3,1)
print(D)

[3 6 9]
(3,)
[[3]
 [6]
 [9]]
(3, 1)
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [6]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(np.sum(A))

print(np.sum(A, axis=0))  # sum of each column
print(np.sum(A, axis=0).shape)

print(np.sum(A, axis=1))  # sum of each row
print(np.sum(A, axis=1).shape)

print(np.sum(A, axis=0, keepdims=True))  # sum of each row
print(np.sum(A, axis=0, keepdims=True).shape)

print(np.sum(A, axis=1, keepdims=True))  # sum of each row
print(np.sum(A, axis=1, keepdims=True).shape)

print(np.max(A, axis=0))  # max of each column
print(np.max(A, axis=0).shape)

print(np.max(A, axis=1))  # max of each row
print(np.max(A, axis=1).shape)

print(np.max(A))


45
[12 15 18]
(3,)
[ 6 15 24]
(3,)
[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)
[7 8 9]
(3,)
[3 6 9]
(3,)
9
