<a href="https://colab.research.google.com/github/laksiri-kingslake/neural-network-from-scratch/blob/main/NeuralNetworks_Coding_From_Scratch_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS

### CODING OUR FIRST NEURON: 3 INPUTS

![Neuron with 3 inputs](./images/neuron-3-input.png)

In [2]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

outputs = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)

print(outputs)

2.3


### CODING OUR SECOND NEURON: 4 INPUTS ###

![Neuron with 4 inputs](./images/neuron-4-input.png)

In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0]*weights[0] +
 inputs[1]*weights[1] +
 inputs[2]*weights[2] +
 inputs[3]*weights[3] + bias)

print(output)

4.8


### CODING OUR FIRST LAYER

![A layer of neurons](./images/neuron-layer.png)

In [ ]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0] #LIST OF WEIGHTS ASSOCIATED WITH 1ST NEURON : W11, W12, W13, W14
weights2 = weights[1] #LIST OF WEIGHTS ASSOCIATED WITH 2ND NEURON : W21, W22, W23, W24
weights3 = weights[2] #LIST OF WEIGHTS ASSOCIATED WITH 3RD NEURON : W31, W32, W33, W34

biases = [bias1, bias2, bias3] = [2, 3, 0.5]

outputs = [
 # Neuron 1:
 inputs[0]*weights1[0] +
 inputs[1]*weights1[1] +
 inputs[2]*weights1[2] +
 inputs[3]*weights1[3] + bias1,
 # Neuron 2:
 inputs[0]*weights2[0] +
 inputs[1]*weights2[1] +
 inputs[2]*weights2[2] +
 inputs[3]*weights2[3] + bias2,
 # Neuron 3:
 inputs[0]*weights3[0] +
 inputs[1]*weights3[1] +
 inputs[2]*weights3[2] +
 inputs[3]*weights3[3] + bias3]

print(outputs)

[4.8, 1.21, 2.385]


#### USING LOOPS FOR BETTER AND EASIER CODING

In [5]:
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
 # Zeroed output of given neuron
 neuron_output = 0
 # For each input and weight to the neuron
 for n_input, weight in zip(inputs, neuron_weights):
 # Multiply this input by associated weight
 # and add to the neuron's output variable
   neuron_output += n_input*weight ## W31*X1 + W32*X2 + W33*X3 + W34*X4
   # Add bias
 neuron_output += neuron_bias ## ## W31*X1 + W32*X2 + W33*X3 + W34*X4 + B3
 # Put neuron's result to the layer's output list
 layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


#### USING NUMPY

##### NumPy dot Product 

1. NumPy dot Product of Vectors

    x = [a1, a2, a3]

    y = [b1, b2, b3]

    np.dot(x, y) = a1*b1 + a2*b2 + a3*b3

In [9]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))  # Output: 32

32


2. NumPy dot product of vector and matrix

    x = [a1, a2, a3] # 1 x 3

    y = [[b11, b12, b13],<br>
         [b21, b22, b23],<br>
         [b31, b32, b33]] # 3 x 3

    np.dot(x, y) = [a1*b11 + a2*b21 + a3*b31, a1*b12 + a2*b22 + a3*b32, a1*b13 + a2*b23 + a3*b33] # 1 x 3

    Let's call<br>
    bn1 = [b11,b21,b31]<br>
    bn2 = [b12,b22,b32]<br>
    bn3 = [b13,b23,b33]<br>
    Then,<br>
    np.dot(x, y) = [np.dot(x,bn1), np.dot(x,bn2), np.dot(x,bn3)] # 1 x 3

    np.dot(y, x) = [[np.dot(bn1, x)],[np.dot(bn2, x)],[np.dot(bn3, x)]]

In [ ]:
y = np.array([[4, 5, 6],[7, 8, 9],[10, 11, 12]]) # 3 x 3 matrix
print(np.dot(x, y))  # Output: 48 54 60 1 x 3 matrix (vector)

[48 54 60]


In [ ]:
print(np.dot(y, x)) # Output: [32  50  48] 3 x 1 matrix (vector)

[32 50 68]


3. NumPy dot product of a matrix and a matrix

    a = [[a11, a12],<br>
         [a21, a22],<br>
         [a31, a32]]<br> # 3 x 2 matrix

    y = [[b11, b12, b13],<br>
         [b21, b22, b23]] # 2 x 3 matrix<br>

    Let's call<br>
    a1 = [a11, a12]<br>
    a2 = [a21, a22]<br>
    a3 = [a31, a32]<br>
    bn1 = [b11,b21]<br>
    bn2 = [b12,b22]<br>
    bn3 = [b13,b23]<br>
    Then,<br>

    np.dot(a, b) = [[np.dot(a1,bn1), np.dot(a1,bn2), np.dot(a1,bn3)],<br>
                    [np.dot(a2,bn1), np.dot(a2,bn2), np.dot(a2,bn3)],<br>
                    [np.dot(a3,bn1), np.dot(a3,bn2), np.dot(a3,bn3)]]     # 3 x 3 matrix

In [12]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # 3 x 2 matrix

b = np.array([[7, 8, 9],
              [10, 11, 12]]) # 2 x 3 matrix

print(np.dot(a, b)) # Output: [[27 30 33] [61 68 75] [95 106 117]] 3 x 3 matrix


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


##### SINGLE NEURON USING NUMPY

![A neuron with np dot product](./images/neuron-np-dot.png)

In [13]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


##### LAYER OF NEURONS USING NUMPY

![A neuron layer with np dot product](./images/neuron-layer-np-dot.png)

In [ ]:
##  In plain Python, we wrote this as a list of lists. With NumPy, this will be a 2-dimensional array, which we’ll call a matrix.

In [14]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vector results in a list of dot products.
#The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other vector

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


##### LAYER OF NEURONS AND BATCH OF DATA USING NUMPY

![A neuron layer with a batch of input](./images/neuron-layer-with-input-batch.png)

###### NEED TO TAKE TRANSPOSE OF WEIGHT MATRIX

![Get transpose of weights matrix](./images/neuron-layer-with-input-batch-weights-transpose.png)

In [15]:
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# NOTE: WE CAN'T TRANSPOSE LISTS IN PYTHON, SO WE HAVE THE CONVERT THE WEIGHTS MATRIX INTO AN ARRAY FIRST
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
